name: CI

on: [push]

permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-
    - name: Run test
      working-directory: .
      run: |
        npm install
        npx playwright install
        CI=true npm test
